// solid-version/src/CodeActions.tsx
import { CPU } from "./ReactiveCPU";

export default function CodeActions() {
    return (
       <div>
            <button type="button" ng-click="run()" ng-hide="isRunning">
                Run
            </button>
            <button type="button" ng-click="runQuickly()" ng-hide="isRunning">
                Run Quickly
            </button>
            <button type="button" ng-click="stop()" ng-show="isRunning">
                Stop
            </button>
            <button type="button" onClick={() => CPU.step()}>
                Step
            </button>
            <button type="button" ng-click="reset()">
                Reset
            </button>
        </div>
)};

// solid-version/src/components/CodeActions.tsx
import { createEffect, createSignal, Show } from "solid-js";
import { CPU } from "../utils/ReactiveCPU";
import { getStateContext } from "../utils/stateContext";

export default function CodeActions() {
    let [state, setState] = getStateContext();
    let [interval, _SetInterval] = createSignal(0);
    let [currentSpeed, setCurrentSpeed] = createSignal(0);

    const run = () => {
        _SetInterval(setInterval(() => {
            CPU.step()
        }, 1000 / state.speed))
        setCurrentSpeed(state.speed)
    }
    const runQuickly = () => {
        setState("quick", true)
        _SetInterval(setInterval(() => {
            CPU.step()
        }, 1000 / 4096))
        setCurrentSpeed(0)

    }
    const stop = () => {
        setState("quick", false)
        clearInterval(interval())
        _SetInterval(0);
    }

    createEffect(() => {
        if (state.speed != currentSpeed() && currentSpeed() != 0) {
            clearInterval(interval())
            run()
        }
    })
    return (
       <div>
            <button type="button" onClick={run} disabled={interval() != 0}>
                Run
            </button>
            <button type="button" onClick={runQuickly} disabled={interval() != 0}>
                Run Quickly
            </button>
            <Show when={interval() != 0}>
                <button type="button" onClick={stop}>
                    Stop
                </button>
            </Show>
       
            <button type="button" onClick={() => CPU.step()}>
                Step
            </button>
            <button type="button">
                Reset
            </button>
        </div>
)};
